name: Run tests
on:
  workflow_call:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  runTests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
